"""rename address

Revision ID: 061cd6b1a93a
Revises: f2979fa4eb11
Create Date: 2023-12-13 00:02:48.489754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '061cd6b1a93a'
down_revision = 'f2979fa4eb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
